// Tạo dữ liệu giả cho các khóa học theo interface ICourse
import { ICourse, IError } from "../../../../interfaces/Course";

const fakeError: IError = {
  code: "",
  description: "",
  type: 0,
};

export const fakeCourseResponse: ICourse = {
  error: fakeError,
  isFailure: false,
  isSuccess: true,
  value: [
    {
      id: "course-1",
      level: 1,
      name: "English for Beginners",
      nextCourse: null,
      lessons: [
        {
          id: "lesson1-1",
          title: "Lesson 1: Introduction",
          order: 1,
          questions: [],
          epEarned: 100,
        },
        {
          id: "lesson1-2",
          title: "Lesson 2: Basic Vocabulary",
          order: 2,
          questions: [],
          epEarned: 110,
        },
        {
          id: "lesson1-3",
          title: "Lesson 3: Basic Grammar",
          order: 3,
          questions: [],
          epEarned: 120,
        },
        {
          id: "lesson1-4",
          title: "Lesson 4: Pronunciation Basics",
          order: 4,
          questions: [],
          epEarned: 130,
        },
        {
          id: "lesson1-5",
          title: "Lesson 5: Listening Skills",
          order: 5,
          questions: [],
          epEarned: 140,
        },
        {
          id: "lesson1-6",
          title: "Lesson 6: Speaking Practice",
          order: 6,
          questions: [],
          epEarned: 150,
        },
        {
          id: "lesson1-7",
          title: "Lesson 7: Reading Comprehension",
          order: 7,
          questions: [],
          epEarned: 160,
        },
        {
          id: "lesson1-8",
          title: "Lesson 8: Writing Skills",
          order: 8,
          questions: [],
          epEarned: 170,
        },
        {
          id: "lesson1-9",
          title: "Lesson 9: Intermediate Concepts",
          order: 9,
          questions: [],
          epEarned: 180,
        },
        {
          id: "lesson1-10",
          title: "Lesson 10: Review and Practice",
          order: 10,
          questions: [],
          epEarned: 190,
        },
      ],
    },
    {
      id: "course-2",
      level: 2,
      name: "Intermediate English",
      nextCourse: null,
      lessons: [
        {
          id: "lesson2-1",
          title: "Lesson 1: Intermediate Conversation",
          order: 1,
          questions: [],
          epEarned: 120,
        },
        {
          id: "lesson2-2",
          title: "Lesson 2: Intermediate Grammar",
          order: 2,
          questions: [],
          epEarned: 130,
        },
        {
          id: "lesson2-3",
          title: "Lesson 3: Listening Skills",
          order: 3,
          questions: [],
          epEarned: 140,
        },
      ],
    },
    {
      id: "course-3",
      level: 3,
      name: "Advanced English",
      nextCourse: null,
      lessons: [
        {
          id: "lesson3-1",
          title: "Lesson 1: Advanced Vocabulary",
          order: 1,
          questions: [],
          epEarned: 150,
        },
        {
          id: "lesson3-2",
          title: "Lesson 2: Advanced Grammar",
          order: 2,
          questions: [],
          epEarned: 160,
        },
        {
          id: "lesson3-3",
          title: "Lesson 3: Idioms and Phrasal Verbs",
          order: 3,
          questions: [],
          epEarned: 170,
        },
      ],
    },
    {
      id: "course-4",
      level: 4,
      name: "Business English",
      nextCourse: null,
      lessons: [
        {
          id: "lesson4-1",
          title: "Lesson 1: Business Communication",
          order: 1,
          questions: [],
          epEarned: 200,
        },
        {
          id: "lesson4-2",
          title: "Lesson 2: Business Writing",
          order: 2,
          questions: [],
          epEarned: 210,
        },
        {
          id: "lesson4-3",
          title: "Lesson 3: Negotiation Skills",
          order: 3,
          questions: [],
          epEarned: 220,
        },
      ],
    },
    {
      id: "course-5",
      level: 5,
      name: "English for Travel",
      nextCourse: null,
      lessons: [
        {
          id: "lesson5-1",
          title: "Lesson 1: Travel Vocabulary",
          order: 1,
          questions: [],
          epEarned: 130,
        },
        {
          id: "lesson5-2",
          title: "Lesson 2: Booking and Reservations",
          order: 2,
          questions: [],
          epEarned: 140,
        },
        {
          id: "lesson5-3",
          title: "Lesson 3: Cultural Tips",
          order: 3,
          questions: [],
          epEarned: 150,
        },
      ],
    },
    {
      id: "course-6",
      level: 1,
      name: "Grammar Essentials",
      nextCourse: null,
      lessons: [
        {
          id: "lesson6-1",
          title: "Lesson 1: Parts of Speech",
          order: 1,
          questions: [],
          epEarned: 110,
        },
        {
          id: "lesson6-2",
          title: "Lesson 2: Tenses",
          order: 2,
          questions: [],
          epEarned: 120,
        },
        {
          id: "lesson6-3",
          title: "Lesson 3: Sentence Structure",
          order: 3,
          questions: [],
          epEarned: 130,
        },
      ],
    },
    {
      id: "course-7",
      level: 2,
      name: "Pronunciation Practice",
      nextCourse: null,
      lessons: [
        {
          id: "lesson7-1",
          title: "Lesson 1: Vowel Sounds",
          order: 1,
          questions: [],
          epEarned: 105,
        },
        {
          id: "lesson7-2",
          title: "Lesson 2: Consonant Sounds",
          order: 2,
          questions: [],
          epEarned: 110,
        },
        {
          id: "lesson7-3",
          title: "Lesson 3: Intonation and Stress",
          order: 3,
          questions: [],
          epEarned: 115,
        },
      ],
    },
    {
      id: "course-8",
      level: 3,
      name: "Conversational English",
      nextCourse: null,
      lessons: [
        {
          id: "lesson8-1",
          title: "Lesson 1: Everyday Conversation",
          order: 1,
          questions: [],
          epEarned: 140,
        },
        {
          id: "lesson8-2",
          title: "Lesson 2: Small Talk",
          order: 2,
          questions: [],
          epEarned: 145,
        },
        {
          id: "lesson8-3",
          title: "Lesson 3: Expressing Opinions",
          order: 3,
          questions: [],
          epEarned: 150,
        },
      ],
    },
    {
      id: "course-9",
      level: 4,
      name: "Exam Preparation",
      nextCourse: null,
      lessons: [
        {
          id: "lesson9-1",
          title: "Lesson 1: Exam Strategies",
          order: 1,
          questions: [],
          epEarned: 160,
        },
        {
          id: "lesson9-2",
          title: "Lesson 2: Practice Tests",
          order: 2,
          questions: [],
          epEarned: 165,
        },
        {
          id: "lesson9-3",
          title: "Lesson 3: Time Management",
          order: 3,
          questions: [],
          epEarned: 170,
        },
      ],
    },
    {
      id: "course-10",
      level: 5,
      name: "English Literature",
      nextCourse: null,
      lessons: [
        {
          id: "lesson10-1",
          title: "Lesson 1: Introduction to Literature",
          order: 1,
          questions: [],
          epEarned: 170,
        },
        {
          id: "lesson10-2",
          title: "Lesson 2: Literary Analysis",
          order: 2,
          questions: [],
          epEarned: 175,
        },
        {
          id: "lesson10-3",
          title: "Lesson 3: Poetry and Prose",
          order: 3,
          questions: [],
          epEarned: 180,
        },
      ],
    },
  ],
};
