export const CourseMockData = [
  {
    name: "English for Beginners",
    level: 1,
    nextCourse: null,
    lessons: [
      {
        title: "Lesson 4",
        xpEarned: 100,
        order: 4,
        questions: [],
        id: "07b0fd41-1dde-45b1-8549-66843f2bacf1",
      },
      {
        title: "Lesson 1",
        xpEarned: 100,
        order: 1,
        questions: [],
        id: "1cdb3056-ef3f-4ebc-9725-0551a599046f",
      },
      {
        title: "Lesson 5",
        xpEarned: 100,
        order: 5,
        questions: [],
        id: "8791bcee-2dbd-4680-99ff-722978988d1a",
      },
      {
        title: "Lesson 2",
        xpEarned: 100,
        order: 2,
        questions: [],
        id: "9951c754-9803-4ce2-96e3-91d3bdf83d07",
      },
      {
        title: "Lesson 3",
        xpEarned: 100,
        order: 3,
        questions: [],
        id: "9e0309af-5f9d-4609-996a-f3aa54788623",
      },
    ],
    id: "503a1f7a-9ac4-41c6-a78e-fecf55c320cb",
  },
  {
    name: "Khóa học 2",
    level: 1,
    nextCourse: null,
    lessons: [
      {
        title: "Bài học 1",
        xpEarned: 100,
        order: 1,
        questions: [],
        id: "course2-lesson1",
      },
      {
        title: "Bài học 2",
        xpEarned: 100,
        order: 2,
        questions: [],
        id: "course2-lesson2",
      },
      {
        title: "Bài học 3",
        xpEarned: 100,
        order: 3,
        questions: [],
        id: "course2-lesson3",
      },
    ],
    id: "uuid-course2",
  },
  {
    name: "Khóa học 3",
    level: 1,
    nextCourse: null,
    lessons: [
      {
        title: "Bài học 1",
        xpEarned: 100,
        order: 1,
        questions: [],
        id: "course3-lesson1",
      },
      {
        title: "Bài học 2",
        xpEarned: 100,
        order: 2,
        questions: [],
        id: "course3-lesson2",
      },
      {
        title: "Bài học 3",
        xpEarned: 100,
        order: 3,
        questions: [],
        id: "course3-lesson3",
      },
    ],
    id: "uuid-course3",
  },
  {
    name: "Khóa học 4",
    level: 1,
    nextCourse: null,
    lessons: [
      {
        title: "Bài học 1",
        xpEarned: 100,
        order: 1,
        questions: [],
        id: "course4-lesson1",
      },
      {
        title: "Bài học 2",
        xpEarned: 100,
        order: 2,
        questions: [],
        id: "course4-lesson2",
      },
      {
        title: "Bài học 3",
        xpEarned: 100,
        order: 3,
        questions: [],
        id: "course4-lesson3",
      },
    ],
    id: "uuid-course4",
  },
  {
    name: "Khóa học 5",
    level: 1,
    nextCourse: null,
    lessons: [
      {
        title: "Bài học 1",
        xpEarned: 100,
        order: 1,
        questions: [],
        id: "course5-lesson1",
      },
      {
        title: "Bài học 2",
        xpEarned: 100,
        order: 2,
        questions: [],
        id: "course5-lesson2",
      },
      {
        title: "Bài học 3",
        xpEarned: 100,
        order: 3,
        questions: [],
        id: "course5-lesson3",
      },
    ],
    id: "uuid-course5",
  },
  {
    name: "Khóa học 6",
    level: 1,
    nextCourse: null,
    lessons: [
      {
        title: "Bài học 1",
        xpEarned: 100,
        order: 1,
        questions: [],
        id: "course6-lesson1",
      },
      {
        title: "Bài học 2",
        xpEarned: 100,
        order: 2,
        questions: [],
        id: "course6-lesson2",
      },
      {
        title: "Bài học 3",
        xpEarned: 100,
        order: 3,
        questions: [],
        id: "course6-lesson3",
      },
    ],
    id: "uuid-course6",
  },
  {
    name: "Khóa học 7",
    level: 1,
    nextCourse: null,
    lessons: [
      {
        title: "Bài học 1",
        xpEarned: 100,
        order: 1,
        questions: [],
        id: "course7-lesson1",
      },
      {
        title: "Bài học 2",
        xpEarned: 100,
        order: 2,
        questions: [],
        id: "course7-lesson2",
      },
      {
        title: "Bài học 3",
        xpEarned: 100,
        order: 3,
        questions: [],
        id: "course7-lesson3",
      },
    ],
    id: "uuid-course7",
  },
  {
    name: "Khóa học 8",
    level: 1,
    nextCourse: null,
    lessons: [
      {
        title: "Bài học 1",
        xpEarned: 100,
        order: 1,
        questions: [],
        id: "course8-lesson1",
      },
      {
        title: "Bài học 2",
        xpEarned: 100,
        order: 2,
        questions: [],
        id: "course8-lesson2",
      },
      {
        title: "Bài học 3",
        xpEarned: 100,
        order: 3,
        questions: [],
        id: "course8-lesson3",
      },
    ],
    id: "uuid-course8",
  },
  {
    name: "Khóa học 9",
    level: 1,
    nextCourse: null,
    lessons: [
      {
        title: "Bài học 1",
        xpEarned: 100,
        order: 1,
        questions: [],
        id: "course9-lesson1",
      },
      {
        title: "Bài học 2",
        xpEarned: 100,
        order: 2,
        questions: [],
        id: "course9-lesson2",
      },
      {
        title: "Bài học 3",
        xpEarned: 100,
        order: 3,
        questions: [],
        id: "course9-lesson3",
      },
    ],
    id: "uuid-course9",
  },
  {
    name: "Khóa học 10",
    level: 1,
    nextCourse: null,
    lessons: [
      {
        title: "Bài học 1",
        xpEarned: 100,
        order: 1,
        questions: [],
        id: "course10-lesson1",
      },
      {
        title: "Bài học 2",
        xpEarned: 100,
        order: 2,
        questions: [],
        id: "course10-lesson2",
      },
      {
        title: "Bài học 3",
        xpEarned: 100,
        order: 3,
        questions: [],
        id: "course10-lesson3",
      },
    ],
    id: "uuid-course10",
  },
  {
    name: "Khóa học 11",
    level: 1,
    nextCourse: null,
    lessons: [
      {
        title: "Bài học 1",
        xpEarned: 100,
        order: 1,
        questions: [],
        id: "course11-lesson1",
      },
      {
        title: "Bài học 2",
        xpEarned: 100,
        order: 2,
        questions: [],
        id: "course11-lesson2",
      },
      {
        title: "Bài học 3",
        xpEarned: 100,
        order: 3,
        questions: [],
        id: "course11-lesson3",
      },
    ],
    id: "uuid-course11",
  },
];
